apiVersion: v1
kind: Service
metadata:
  name: {{ include "argus-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argus-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "argus-api.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
