apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argus-detector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argus-detector.labels" . | nindent 4 }}
